language: node_js
node_js:
    - "6"
script: npm test
after_success:
    - npm run coveralls
services:
    - mongodb
notifications:
    - webhooks: https://coveralls.io/webhook?repo_token=ZxG8OIzaPY9iMBN5BR4vzBI9DCoq1kyYx    
